version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/node:15.0.1-browsers'
        auth:
          username: davidh80
          password: Docker$123!
    working_directory: ~/repo

    steps:
      - checkout
      - npm install geckodriver
      - npm install chromedriver

      - run: npm install

      # run tests!
      - run: npm test
      - run: npm run test